name: Continuous integration

on:
  push:
    branches:
      - 'main'
  pull_request:
    branches:
      - '*'
jobs:
  build_test_pack:
    name: Build, test & pack
    runs-on: ubuntu-latest
    env:
      buildConfiguration: release
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-dotnet@v4
        with:
         dotnet-version: '9.x'
      - name: Get next version
        uses: reecetech/version-increment@2024.10.1
        id: version
        with:
          scheme: semver
          increment: patch
      - name: Set up Node.js ⚙️
        uses: actions/setup-node@v3
        with:
            node-version: '20'
      - name: Setup .NET Core @ Latest
        uses: actions/setup-dotnet@v3
        with:
          source-url: https://nuget.pkg.github.com/${{ github.repository_owner }}/index.json
        env:
          NUGET_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}
      - name: Install react dependencies
        run: npm ci
        working-directory: react
      - name: Run react build
        run: npm run build
        working-directory: react
      - name: Restore
        run: dotnet restore lunchin.Optimizely.Cloud.Extensions.sln --configfile NuGet.config
      - name: Build 
        run: dotnet build --no-restore --configuration $buildConfiguration /p:Version=${{ steps.version.outputs.version }}
      - name: Test
        run: dotnet test --no-build --configuration $buildConfiguration
      - name: Pack
        shell: pwsh
        run: |
          ./build/pack.ps1 -version ${{ steps.semvers.outputs.patch }}-pre
      - name: Publish packages
        run: dotnet nuget push artifacts/**/*.nupkg --skip-duplicate -k ${{ secrets.GITHUB_TOKEN }}
      - name: Tag branch
        run: |
          git tag -f -a ${{ steps.version.outputs.version }} -m "Release ${{ steps.version.outputs.version }}."
          git push -f origin ${{ steps.version.outputs.version }}
